---

- name: Check PHP is already installed
  shell: php --version
  register: php_exist
  ignore_errors: yes

- name: Fail if PHP was not properly installed
  fail: msg="PHP was not properly installed. Please have a working php-cli."
  when: "'not found' in php_exist.stderr"

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -d allow_url_fopen=1 -- --filename=composer -- --install-dir=/usr/local/bin
  tags: composer

- name: Make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file
  tags: composer
